config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w(chinese italian japanese french belgian), message: "%{value} is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all     # GET /restaurants
  end

  def show
    @restaurants = Restaurant.find(params[:id])     # GET /restaurants/:id
  end

  def new
     @restaurant = Restaurant.new      # POST /restaurants
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)   # GET /restaurants/new
    @restaurant.save
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    if @review.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <form class="form-inline">
    <ul>
      <li><h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4></li>
    </ul>
  </form>
<% end %>

<br>
<p><%= link_to " + Add New Restaurat", new_restaurant_path %></p>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>

  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>


  <%= f.submit "add a restaurant", class: "btn btn-primary" %>


<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurants.name%></h1>

<h2><%= @restaurants.address%></h2>

<br>

<p>
    <%= link_to "Add a Review", new_restaurant_review_path(@restaurants) %>
    <br>
    <br>
    <%= link_to "Back to list", restaurants_path %>
</p>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>

  <% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :content %>
  <%= f.input :rating %>

  <%= f.submit "add a review", class: "btn btn-primary" %>


<% end %>